---
title: "Installing R and RStudio"
description: Instructions for installing R and RStudio on your computer
---

To participate in the HDAT9800 course you will need a copy of both `R` and `RStudio` installed on your computer. Both `R` and `RStudio` are free, open-source software available at no cost and able to be installed on as many computers as you wish at no charge.

`R` is a programming language and associated software libraries designed for statistical and data science computing. It is the "engine", but provides only simple user interfaces. `RStudio` is an IDE (integrated development environment) application designed specifically for `R` although it works with other programming languages such as Python. It provides a very convenient and easy-to-use interface for working with `R`.

First download `R` (choose the installation package appropriate for your computer's operating system - Win/MacOS/Linux) from CRAN (the Comprehensive R Archive Network, which distributes R software worldwide via a series of mirror sites) at [https://cloud.r-project.org](https://cloud.r-project.org). Download the `R` package appropriate for your computer's operating system (Windows, Apple macOS or Linux) from the "Download and Install R" section at the top of the CRAN distribution page. Locate the downloaded package file in your downloads directory, and open it to run it. Just use the default settings for the installation.

Next, download RStudio Desktop from [https://www.rstudio.com/products/rstudio/](https://www.rstudio.com/products/rstudio/).  Select the free Open Source Edition. It should take you to [this page](https://www.rstudio.com/products/rstudio/download/#download). Download the package appropriate for your computer's operating system (it should detect that and offer the correct package next to step 2. on the Rstudio downlaod page at [https://www.rstudio.com/products/rstudio/download/#download](https://www.rstudio.com/products/rstudio/download/#download). Locate the downloaded file in your Downloads folder, open it to initiate the RStudio installation wizard.Again, just follow the installation default options offered.

Open `RStudio` - when it opens it should automatically detect and link to the `R` installation on your computer. 

You can learn more about what's available in RStudio Desktop here: [https://www.rstudio.com/products/rstudio/#Desktop](https://www.rstudio.com/products/rstudio/#Desktop)

You will also need to install and configure `git` on your computer. This is covered in the tutorials on `git` and `GitHub` available on the [Chapter 1](chapter1.html) page for the HDAT9800 course.

     
     
     
     


